-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://github.com/pgadmin-org/pgadmin4/issues/new/choose if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE IF NOT EXISTS public.author
(
    id bigint NOT NULL GENERATED ALWAYS AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    name character varying(10) COLLATE pg_catalog."default" NOT NULL,
    intro text COLLATE pg_catalog."default",
    img character varying(500) COLLATE pg_catalog."default",
    birth character varying(11) COLLATE pg_catalog."default",
    created_date timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_date timestamp without time zone,
    author_code character varying(50) COLLATE pg_catalog."default",
    CONSTRAINT pk_author PRIMARY KEY (id),
    CONSTRAINT uq_author_code UNIQUE (author_code)
);

COMMENT ON COLUMN public.author.id
    IS '일련번호';

COMMENT ON COLUMN public.author.name
    IS '이름';

COMMENT ON COLUMN public.author.intro
    IS '소개글';

COMMENT ON COLUMN public.author.img
    IS '작가 이미지';

COMMENT ON COLUMN public.author.birth
    IS '생년월일';

COMMENT ON COLUMN public.author.created_date
    IS '등록일자';

COMMENT ON COLUMN public.author.updated_date
    IS '수정일자';

COMMENT ON COLUMN public.author.author_code
    IS '교보문고 작가 코드';

CREATE TABLE IF NOT EXISTS public.author_book_map
(
    id bigint NOT NULL GENERATED ALWAYS AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    book_id bigint NOT NULL,
    author_id bigint NOT NULL,
    role character varying(20) COLLATE pg_catalog."default" DEFAULT '지은이'::character varying,
    CONSTRAINT pk_author_book_map PRIMARY KEY (id),
    CONSTRAINT uq_author_book UNIQUE (book_id, author_id)
);

COMMENT ON COLUMN public.author_book_map.id
    IS '일련번호';

COMMENT ON COLUMN public.author_book_map.book_id
    IS '책 일련번호';

COMMENT ON COLUMN public.author_book_map.author_id
    IS '작가 일련번호';

COMMENT ON COLUMN public.author_book_map.role
    IS '역할(지은이, 옮긴이 등)';

CREATE TABLE IF NOT EXISTS public.book
(
    id bigint NOT NULL GENERATED ALWAYS AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    title character varying(100) COLLATE pg_catalog."default" NOT NULL,
    publisher_id bigint NOT NULL,
    rating integer,
    pages integer,
    description text COLLATE pg_catalog."default",
    toc text COLLATE pg_catalog."default",
    isbn character varying(20) COLLATE pg_catalog."default",
    price integer,
    published_date date,
    size character varying(50) COLLATE pg_catalog."default",
    img character varying(500) COLLATE pg_catalog."default",
    country_id bigint NOT NULL,
    created_date timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_date timestamp without time zone,
    CONSTRAINT pk_book PRIMARY KEY (id),
    CONSTRAINT uq_book_isbn UNIQUE (isbn)
);

COMMENT ON COLUMN public.book.id
    IS '일련번호';

COMMENT ON COLUMN public.book.title
    IS '책 제목';

COMMENT ON COLUMN public.book.publisher_id
    IS '출판사';

COMMENT ON COLUMN public.book.rating
    IS '평균 별점';

COMMENT ON COLUMN public.book.pages
    IS '페이지 수';

COMMENT ON COLUMN public.book.description
    IS '책 소개 (줄거리)';

COMMENT ON COLUMN public.book.toc
    IS '목차(table of contents)';

COMMENT ON COLUMN public.book.isbn
    IS '책 ISBN';

COMMENT ON COLUMN public.book.price
    IS '정가';

COMMENT ON COLUMN public.book.published_date
    IS '출판일자';

COMMENT ON COLUMN public.book.size
    IS '책 실물 크기';

COMMENT ON COLUMN public.book.img
    IS '표지 이미지 링크';

COMMENT ON COLUMN public.book.country_id
    IS '국가 일련번호';

COMMENT ON COLUMN public.book.created_date
    IS '등록일자';

COMMENT ON COLUMN public.book.updated_date
    IS '수정일자';

CREATE TABLE IF NOT EXISTS public.book_review
(
    id bigint NOT NULL GENERATED ALWAYS AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    book_id bigint NOT NULL,
    user_id bigint NOT NULL,
    content text COLLATE pg_catalog."default",
    rating integer NOT NULL,
    likes integer,
    created_date timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_date timestamp without time zone,
    CONSTRAINT pk_book_review PRIMARY KEY (id)
);

COMMENT ON COLUMN public.book_review.id
    IS '일련번호';

COMMENT ON COLUMN public.book_review.book_id
    IS '책 일련번호';

COMMENT ON COLUMN public.book_review.user_id
    IS '회원 일련번호';

COMMENT ON COLUMN public.book_review.content
    IS '내용';

COMMENT ON COLUMN public.book_review.rating
    IS '별점';

COMMENT ON COLUMN public.book_review.likes
    IS '좋아요';

COMMENT ON COLUMN public.book_review.created_date
    IS '날짜';

COMMENT ON COLUMN public.book_review.updated_date
    IS '수정 날짜';

CREATE TABLE IF NOT EXISTS public.country
(
    id bigint NOT NULL GENERATED ALWAYS AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    name character varying(50) COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT pk_country PRIMARY KEY (id)
);

COMMENT ON COLUMN public.country.id
    IS '일련번호';

COMMENT ON COLUMN public.country.name
    IS '국가 이름';

CREATE TABLE IF NOT EXISTS public.genre
(
    id bigint NOT NULL GENERATED ALWAYS AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    parent_id bigint,
    name character varying(10) COLLATE pg_catalog."default" NOT NULL,
    depth integer,
    sort_order integer,
    CONSTRAINT pk_genre PRIMARY KEY (id)
);

COMMENT ON COLUMN public.genre.id
    IS '일련번호';

COMMENT ON COLUMN public.genre.parent_id
    IS '부모 장르';

COMMENT ON COLUMN public.genre.name
    IS '이름';

COMMENT ON COLUMN public.genre.depth
    IS '대/중/소 분류';

COMMENT ON COLUMN public.genre.sort_order
    IS '보여지는 순서';

CREATE TABLE IF NOT EXISTS public.genre_book_map
(
    id bigint NOT NULL GENERATED ALWAYS AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    genre_id bigint NOT NULL,
    book_id bigint NOT NULL,
    CONSTRAINT pk_genre_book_map PRIMARY KEY (id)
);

COMMENT ON COLUMN public.genre_book_map.id
    IS '일련번호';

COMMENT ON COLUMN public.genre_book_map.genre_id
    IS '장르 일련번호';

COMMENT ON COLUMN public.genre_book_map.book_id
    IS '책 일련번호';

CREATE TABLE IF NOT EXISTS public.publisher
(
    id bigint NOT NULL GENERATED ALWAYS AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    name character varying(100) COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT pk_publisher PRIMARY KEY (id),
    CONSTRAINT uq_publisher_name UNIQUE (name)
);

COMMENT ON COLUMN public.publisher.id
    IS '일련번호';

COMMENT ON COLUMN public.publisher.name
    IS '이름';

CREATE TABLE IF NOT EXISTS public.users
(
    id bigint NOT NULL GENERATED ALWAYS AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    name character varying(10) COLLATE pg_catalog."default" NOT NULL,
    email character varying(50) COLLATE pg_catalog."default" NOT NULL,
    user_id character varying(20) COLLATE pg_catalog."default" NOT NULL,
    pwd character varying(100) COLLATE pg_catalog."default" NOT NULL,
    nickname character varying(50) COLLATE pg_catalog."default",
    img character varying(500) COLLATE pg_catalog."default",
    birth date,
    intro text COLLATE pg_catalog."default",
    sign_up_type character varying(100) COLLATE pg_catalog."default",
    created_date timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_date timestamp without time zone,
    CONSTRAINT pk_users PRIMARY KEY (id)
);

COMMENT ON COLUMN public.users.id
    IS '일련번호';

COMMENT ON COLUMN public.users.name
    IS '이름';

COMMENT ON COLUMN public.users.email
    IS '이메일';

COMMENT ON COLUMN public.users.user_id
    IS '아이디';

COMMENT ON COLUMN public.users.pwd
    IS '비밀번호';

COMMENT ON COLUMN public.users.nickname
    IS '닉네임';

COMMENT ON COLUMN public.users.img
    IS '프로필 이미지';

COMMENT ON COLUMN public.users.birth
    IS '생년월일';

COMMENT ON COLUMN public.users.intro
    IS '소개글';

COMMENT ON COLUMN public.users.sign_up_type
    IS '소셜 로그인 타입';

COMMENT ON COLUMN public.users.created_date
    IS '등록일자';

COMMENT ON COLUMN public.users.updated_date
    IS '업데이트 일자';

ALTER TABLE IF EXISTS public.author_book_map
    ADD CONSTRAINT fk_author_book_map_author FOREIGN KEY (author_id)
        REFERENCES public.author (id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.author_book_map
    ADD CONSTRAINT fk_author_book_map_book FOREIGN KEY (book_id)
        REFERENCES public.book (id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.book
    ADD CONSTRAINT fk_book_country FOREIGN KEY (country_id)
        REFERENCES public.country (id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.book
    ADD CONSTRAINT fk_book_publisher FOREIGN KEY (publisher_id)
        REFERENCES public.publisher (id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.book_review
    ADD CONSTRAINT fk_book_review_book FOREIGN KEY (book_id)
        REFERENCES public.book (id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.book_review
    ADD CONSTRAINT fk_book_review_user FOREIGN KEY (user_id)
        REFERENCES public.users (id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.genre_book_map
    ADD CONSTRAINT fk_genre_book_map_book FOREIGN KEY (book_id)
        REFERENCES public.book (id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.genre_book_map
    ADD CONSTRAINT fk_genre_book_map_genre FOREIGN KEY (genre_id)
        REFERENCES public.genre (id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION;

END;